stages:
  - lint
  - test

lint_code:
  stage: lint
  image: python:3.10
  script:
    - git clone https://gitlab.com/lappis-unb/decidimbr/decidim-whatsapp-integration/airflow/hawk-ops.git
    - cd hawk-ops
    - pip install -r dags/tests/requirements.txt
    - pip install black flake8
    - black --check dags/
    - flake8 dags/
  only:
    - main
    - development

run_tests:
  stage: test
  image: python:3.10
  script:
    - cd hawk-ops
    - pip install -r dags/tests/requirements.txt
    - pytest -v dags/tests
  only:
    - main
    - development
  when: on_success
